myproject/models.py
from . import db
from flask_login import UserMixin
from sqlalchemy.sql import func

class Note(db.Model):
    id =  db.Column(db.Integer, primary_key=True)
    data = db.Column(db.String(10000))
    user_id= db.Column(db.Integer,db.ForeignKey('user.id'))

class User(db.Model,UserMixin):
    id = db.Column(db.Integer, primary_key = True)
    email = db.Column(db.String(150))
    password = db.Column(db.String(150))
    username = db.Column(db.String(150))
    notes = db.relationship('Note')

myproject/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from os import path
from flask_login import LoginManager

db = SQLAlchemy()
DB_NAME = "database.db"

def create_app():
    app = Flask(__name__)
    app.config['SECRET_KEY']='hadkjbkajhdbjcdba'
    app.config['SQLALCHEMY_DATABASE_URI'] = f'sqlite:///{DB_NAME}'
    app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = True
    db.init_app(app)


    
    from .views import views
    from .auth import auth

    app.register_blueprint(views,url_prefix='/')
    app.register_blueprint(auth,url_prefix='/')

    from .models import User,Note

    create_database(app)  

    login_manager = LoginManager()
    login_manager.login_view = 'auth.login'
    login_manager.init_app(app)

    @login_manager.user_loader
    def load_user(id):
        return User.query.get(int(id))  

    return app

def create_database(app):
    if not path.exists('website/' + DB_NAME):
        db.create_all(app=app)
        print("Created database")

myproject/auth.py
from flask import Blueprint,render_template, request , flash ,redirect,url_for
from .models import User
from werkzeug.security import generate_password_hash,check_password_hash
from . import db
from flask_login import login_user , login_required ,logout_user , current_user


auth = Blueprint('auth',__name__)

@auth.route('/signup',methods=['GET','POST'])
def signup():
    if request.method == "POST":
        username = request.form.get('username')
        email = request.form.get('email')
        password1 = request.form.get('password1')
        password2 = request.form.get('password2')
        user = User.query.filter_by(username=username).first()

        if len(username) < 3:
            flash('username must be greater then 3 character.',category='error')
        elif user :
            flash('username already exists',category='error')
        elif len(email) < 4:
            flash('username must be greater then 3 character.',category='error')
        elif len(password1) < 4:
            flash('password must be greater then 3 character.',category='error')
        elif password1 != password2:
            flash('password not matching',category='error')
        
        else:
            new_user = User(email=email,username=username,password=generate_password_hash(password1,method="sha256"))
            db.session.add(new_user)
            db.session.commit()
            login_user(user, remember=True)
            flash("account created",category='success')
            return redirect(url_for('views.home'))
    
        return render_template("signup.html")
    else:
        return render_template("signup.html",user=current_user)    

@auth.route('/login', methods=['GET','POST'])
def login():
    if request.method == "POST":
        username = request.form.get('username')
        password = request.form.get('password')
        user = User.query.filter_by(username=username).first()
        if user:
            if check_password_hash(user.password,password):
                flash('loggedin successfully',category='success')
                login_user(user, remember=True)
                return redirect(url_for('views.home'))
            else:
                flash('incorrect password, try again !!!',category='error')
        else:
            flash('incorrect username, try again !!!',category='error')

    else:
        return render_template("login.html", user=current_user)

@auth.route('/logout')
@login_required
def logout():
    logout_user()
    flash('logged out successfully !!!',category='success')
    return redirect(url_for('auth.login'))

myproject/views.py
from flask import Blueprint,render_template,request,flash,redirect,url_for
from flask_login import  login_required , current_user
from .models import Note
from . import db


views = Blueprint('views',__name__)

@views.route('/',methods=['GET','POST'])
@login_required
def home():
    if request.method == 'POST':
        note = request.form.get('note')

        if len(note) < 1:
            flash('note is too short!',category='error')
        else:
            new_note = Note(data=note,user_id=current_user.id)  
            db.session.add(new_note)
            db.session.commit()
            flash('note added!',category='success')
    return render_template("home.html",user=current_user)

@views.route('/<int:id>',methods=['GET','POST']) 
@login_required
def delete(id):
    datatodelete = Note.query.get(id)
    db.session.delete(datatodelete)
    db.session.commit()
    flash('note deleted',category='success')
    return redirect(url_for('views.home'))
       

myproject/templates/base.html
<!doctype html>
<html lang="en">
  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">


    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title> {% block title %}{% endblock %} </title>
  </head>
  <body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
    {% if user.is_authenticated %}
      <li class="nav-item">
        <a class="nav-link" href="{{ url_for ('views.home')}}">Home</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{{ url_for ('auth.logout')}}">Logout</a>
      </li>
      {% else %}
      <li class="nav-item">
        <a class="nav-link" href="{{ url_for ('auth.login')}}">Login</a>
      </li>
      <li class="nav-item ">
        <a class="nav-link " href="{{ url_for ('auth.signup')}}">SignUp</a>
      </li>
      {% endif %}
    </ul>
  </div>
</nav>
{% with messages=get_flashed_messages(with_categories=true) %}
{% if messages %}
  {% for category, message in messages %}
 {% if category =="error" %}
 
  <div class="alert alert-danger alert-dismissable fade show" role="alert">
  {{message}}
  <button type="button" class="close" data-dismiss="alert">
  <span aria-hidden="true">&times;</span>
  </button>
  </div>
 {% else %}
  <div class="alert alert-success alert-dismissable fade show" role="alert">
  {{message}}
  <button type="button" class="close" data-dismiss="alert">
  <span aria-hidden="true">&times;</span>
  </button>
  </div>

 {% endif %}
{% endfor %}
{% endif %}

{% endwith %}
    {% block content %}{% endblock %}
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

myproject/templates/home.html
{% extends "base.html" %}
{% block title %}
home
{% endblock title  %}

{% block content %}
<div class="container">

    <h1 align="center">Notes</h1>
    <ul class="list-group list-group-flush" id="notes">
        {% for note in user.notes %}
        <li class="list-group-item">{{ note.data}}
            <a href="{{ url_for('views.delete', id = note.id) }}"> <button type="button" class="close" > <span aria-hidden="true">&times;</span></button> </a>   
        </li>
    {% endfor %}
</ul>
<form action="" method="post">
    <textarea name="note" id="note" class="form-control" ></textarea>
    <br>
    <div align="center">
        <button type="submit" class="btn btn-primary">Add note</button>
    </div>
    
</form>
</div>
{% endblock content %}

myproject/templates/login.html
{% extends "base.html" %}
{% block title %}
login
{% endblock %}

{% block content %}
<form method="post">
    <div class="container">
        <h1>Login</h1>
    <div class="form-group mt-3">
        <label for="username">Enter Username</label>
        <input type="text" class="form-control" id="username" name="username" placeholder="Enter Username">
    </div>
    <div class="form-group">
        <label for="exampleInputPassword1">Enter Password</label>
        <input type="password" class="form-control" id="exampleInputPassword1" name="password" placeholder="Enter Password">
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
    </div>
</form>

{% endblock %}

myproject/templates/signup.html
{% extends "base.html" %}
{% block title %}
SignUp
{% endblock title  %}

{% block content %}
<form action="" method="post">
    <div class="container">
        <h1>SignUp</h1>
    <div class="form-group mt-3">
        <label for="username">Enter Username</label>
        <input type="text" class="form-control" id="username" name="username" placeholder="Enter Username">
    </div>
    <div class="form-group">
        <label for="exampleInputEmail1">Enter Email</label>
        <input type="email" class="form-control" id="exampleInputEmail1" name="email" aria-describedby="emailHelp" placeholder="Enter email">
    </div>
    <div class="form-group">
        <label for="exampleInputPassword1">Password</label>
        <input type="password" class="form-control" id="exampleInputPassword1" name="password1" placeholder="Password">
    </div>
    <div class="form-group">
        <label for="InputPassword2">Password(confirm)</label>
        <input type="password" class="form-control" id="InputPassword2" name="password2" placeholder="confirm Password">
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>


{% endblock content %}